pub const APPLY_THREADS_PER_BLOCK: u32 = 256;
pub const EMBEDDING_GRAD_THREADS_PER_BLOCK: u32 = 256;
pub const MATRIX_THREADS_PER_BLOCK: u32 = 256;

pub(super) const WARP_SIZE: u32 = 32;
pub(super) const WARPS_PER_BLOCK: u32 = MATRIX_THREADS_PER_BLOCK / WARP_SIZE;
