#[macro_use]
mod metric_fields;

mod attention_core_scratch;
mod backward;
mod batch;
mod buffers;
mod data;
mod debug_metrics;
mod device_buffer;
mod diagnostics;
mod env;
mod eval;
mod forward;
mod generate;
mod grad_block;
mod grad_clip;
mod grads;
mod launch;
mod learning_rate;
mod linear_scratch;
mod metric_accumulator;
mod next_latent;
mod numeric_metric;
mod optimizer;
mod optimizer_apply;
mod optimizer_aurora;
mod optimizer_state;
mod optimizer_tc_scratch;
pub(crate) mod runtime;
mod save;
mod schedule_free;
mod scratch;
mod stats;
mod tape;
mod tape_block;
mod tape_leaf;
mod text_metric;
mod trainer;
mod update_skip;

pub use batch::{ReusableTokenBatch, TokenBatch};
pub use data::TokenDataLoader;
pub use generate::SamplingConfig;
pub(crate) use launch::launch_from_env;
pub use stats::{OptimizerTrace, TrainStats};
pub use trainer::Trainer;
