pub struct TrainingDiagnostics {
    pub update_count: usize,
    pub positive_update_dot_count: usize,
    pub zero_grad_changed_count: usize,
    pub max_update_to_weight_rms: f32,
    pub dlogits_rms: f32,
    pub dlogits_max: f32,
    pub d_lm_head_rms: f32,
    pub d_lm_head_max: f32,
    pub d_embedding_rms: f32,
    pub d_embedding_max: f32,
    pub token_embedding_global_before: f32,
    pub token_embedding_global_after: f32,
    pub token_embedding_changed_bytes: usize,
    pub token_embedding_hash_before: u64,
    pub token_embedding_hash_after: u64,
    pub updates: Vec<TensorUpdateDiagnostics>,
}

pub struct TensorUpdateDiagnostics {
    pub name: String,
    pub len: usize,
    pub grad_rms: f32,
    pub grad_max: f32,
    pub grad_nonzero: usize,
    pub grad_finite: bool,
    pub weight_rms_before: f32,
    pub weight_rms_after: f32,
    pub delta_rms: f32,
    pub delta_max: f32,
    pub update_to_weight_rms: f32,
    pub delta_grad_dot: f32,
    pub delta_grad_cos: f32,
    pub predicted_delta_rms: f32,
    pub predicted_delta_grad_dot: f32,
    pub predicted_delta_grad_cos: f32,
    pub quant_error_rms: f32,
    pub quant_error_to_predicted_delta_rms: f32,
    pub changed_bytes: usize,
    pub changed_scales: usize,
    pub global_before: f32,
    pub global_after: f32,
}
